### PR TITLE
Removed numba jit from smooth function

### PR DESCRIPTION
**Pull request by philippjfr**
- [x] Fixes https://github.com/pyviz/datashader/issues/670

### CODE REVIEW

**Comment by jbednar** [comment]
Have you tested whether this affects performance?

**Comment by philippjfr** [comment]
Not yet, I'll do that now.

**Comment by philippjfr** [comment]
Can't see any difference, with or without the decorator I get 240-250 ms on the example in the linked issue.

**Comment by jbednar** [comment]
Ok, sounds good.  Looks like the tests are calling something deprecated in dask?  "The dask.set_options function has been deprecated. Please use dask.config.set instead"?

**Comment by philippjfr** [comment]
I thought we had already don that.

**Comment by philippjfr** [comment]
Ah it's just one test. Want me to update that in this PR?

**Comment by jbednar** [comment]
Thanks.  I don't think we need to pin dask as a result, since this is just for the test suite, which isn't tested with older dasks.

**Pull request merged**
