### PR TITLE
Removing topics

### PR DESCRIPTION
**Pull request by jsignell**
Topics are moving to pyviz-topics/examples so they no longer need to be here.

### CODE REVIEW

**Comment by jbednar** [comment]
Also need to move nyc_taxi-nongeo.ipynb (never categorized when topics/ were created, but can now be part of the nyc_taxi project).  And need to update docs to point to pyviz_topics/examples/ instead, but as that's still in flux, presumably can't complete that?

**Comment by jsignell** [comment]
Right this is not quite ready yet, need to build the static website version of pyviz-topics/examples

**Comment by jbednar** [comment]
It's ok to merge this to unblock other PRs, as long as we'll deal with that before the next release.

**Comment by jsignell** [comment]
Ok then I'll merge.

**Pull request merged**
